service: employee-manager

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: jprieto
  stage: ${opt:stage}
  region: ${opt:region}

functions:
  getEmployees:
    handler: infraestructure/handlers/employees_handler.getEmployees
    events:
      - http:
          path: employees_handler # https:://domain.com/stage/employees
          method: get

plugins:
  - serverless-offline
