service: employee-manager

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: jprieto
  stage: ${opt:stage}
  region: ${opt:region}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello # https:://domain.com/stage/hello
          method: get

plugins:
  - serverless-offline
