service: employee-manager

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: jprieto
  stage: ${opt:stage}
  region: ${opt:region}

functions:
  getEmployees:
    handler: infraestructure/handlers/employees_handler.getEmployees
    events:
      - http:
          path: employees_handler # https:://domain.com/stage/employees
          method: get
  createEmployees:
    handler: infraestructure/handlers/employees_handler.createEmployees
    events:
      - http:
          path: employees_handler # https:://domain.com/stage/employees
          method: post
  updateEmployees:
    handler: infraestructure/handlers/employees_handler.updateEmployees
    events:
      - http:
          path: employees_handler/{id} # https:://domain.com/stage/employees/{id}
          method: put
  deleteEmployees:
    handler: infraestructure/handlers/employees_handler.deleteEmployees
    events:
      - http:
          path: employees_handler/{id} # https:://domain.com/stage/employees/{id}
          method: delete
  getEmployee:
    handler: infraestructure/handlers/employees_handler.getEmployee
    events:
      - http:
          path: employees_handler/{id} # https:://domain.com/stage/employees/{id}
          method: get

plugins:
  - serverless-offline
